language: python

# Setting sudo to false will cause Travis to use Containers (default in the meantime)
sudo: false

services:
    - docker

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq unixodbc unixodbc-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libodbcinst.so.1 /usr/lib/x86_64-linux-gnu/libodbcinst.so.2

# build all flavors
script: 
  - ./build --flavor=mini
  - ./export --flavor=mini
  - ./test --flavor mini
