language: python

# Setting sudo to false will cause Travis to use Containers (default in the meantime)
sudo: false

services:
    - docker


# build all flavors
script: 
   - ./build --flavor=mini
   - ./export --flavor=mini
   - ./test --flavor mini
